#!/bin/bash
export NEXT_PUBLIC_SUPABASE_URL="https://lztvbovrriomgjtvaiqs.supabase.co"
export NEXT_PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6dHZib3ZycmlvbWdqdHZhaXFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4Mzg1MzIsImV4cCI6MjA3NjQxNDUzMn0.NMTMAEcXB_xhqXiuq1oELN9NxAWWgH3QqrJIv2WU1-c"

npx tsx src/lib/test-connection.ts